/* ═══════════════════════════════════════════════════════════════════════
   A&D Constellation — shared dataset
   Loaded by BOTH views via <script src="data.js">. A plain script tag
   works under file:// where fetch() would be blocked by CORS, which is
   how we keep "opens by double-click" and still have one source of truth.

   ── HONESTY NOTE ──────────────────────────────────────────────────────
   Two different kinds of claim live in this file, and they have different
   reliability:

   1. FACTS with a `src` field — checked against a named public source on
      2026-09-17. Quote these.
   2. SCORES — `domestic` (0–100) and `risk` — are ANALYST JUDGEMENT, not
      measured data. They are a defensible reading of the sourced facts,
      not a statistic. Never present a score as a number someone else
      published. Phase 3 replaces the ones that can be replaced with real
      USGS net-import-reliance figures.
   ══════════════════════════════════════════════════════════════════════ */

window.AD = (function () {

/* ─── 1. CAPABILITY CLUSTERS (constellation view) ─────────────────── */
const CAPS = [
  ['autonomy',   'Autonomy & AI'],
  ['launch',     'Launch'],
  ['space',      'Space Systems & Satcom'],
  ['c2',         'C2 & Decision Software'],
  ['ew',         'Electronic Warfare & Spectrum'],
  ['hyper',      'Hypersonics & Propulsion'],
  ['cuas',       'Counter-UAS & Air Defense'],
  ['maritime',   'Maritime Autonomy'],
  ['mfg',        'Advanced Manufacturing'],
];

/* ─── 2. ORGANISATIONS (constellation view) ───────────────────────── */
// [name, type, caps[], investors[], buyers[], hq, stage, note]
const ORGS = [
  ['Lockheed Martin','prime',['hyper','space','cuas'],[],['af','navy','sda'],'Bethesda, MD','Public',
   'Largest defense contractor by revenue. MBA entry is usually corporate strategy, program finance, or the LM Ventures / Skunk Works commercial team.'],
  ['RTX','prime',['cuas','ew','hyper'],[],['af','army'],'Arlington, VA','Public',
   'Raytheon + Collins + Pratt. Effectors and sensors. MBA paths: business development, supply-chain transformation, M&A.'],
  ['Northrop Grumman','prime',['space','ew','hyper'],[],['af','nro','sda'],'Falls Church, VA','Public',
   'B-21, Sentinel, classified space. One of only two large solid-rocket-motor houses. Heavy program-management culture.'],
  ['General Dynamics','prime',['maritime','c2'],[],['navy','army'],'Reston, VA','Public',
   'Submarines, combat vehicles, GDIT services. Decentralized — recruit into a business unit, not the HQ.'],
  ['Boeing Defense','prime',['space','hyper'],[],['af','navy'],'Arlington, VA','Public',
   'Fixed-price program losses have made this a turnaround story. Interesting if you want operational restructuring reps.'],
  ['L3Harris','prime',['ew','space','hyper'],[],['af','socom'],'Melbourne, FL','Public',
   'Acquisitive mid-tier prime; bought Aerojet Rocketdyne. Received a rare $1B direct Pentagon investment in its rocket motor business in Jan 2026.'],
  ['Leidos','prime',['c2','autonomy'],[],['army','diu'],'Reston, VA','Public',
   'Services and integration rather than hardware. Lower margin, faster hiring, more consulting-like work.'],
  ['BAE Systems Inc','prime',['ew','space'],[],['af','navy'],'Falls Church, VA','Public',
   'US arm of the UK prime, ring-fenced for classified work. Operates Holston and Radford Army Ammunition Plants — the US energetics base.'],
  ['GE Aerospace','prime',['hyper','mfg'],[],['af','navy'],'Evendale, OH','Public',
   'Engines, and therefore the single largest consumer of superalloy castings. Expects airfoil demand up >30% by 2030.'],
  ['Howmet Aerospace','prime',['mfg'],[],['af','navy'],'Pittsburgh, PA','Public',
   'Forgings, castings, fasteners. Unglamorous and structurally critical — the castings queue runs through firms like this.'],

  ['Anduril','dtech',['autonomy','cuas','c2'],['fp','a16z','8vc','gc'],['socom','diu','army'],'Costa Mesa, CA','Late',
   'The category definer: builds product on its own balance sheet, then sells. Bought Adranos for additive solid rocket motors. Hires MBAs into growth, corp dev, and business-lead roles owning a product P&L.'],
  ['Palantir','dtech',['c2','autonomy'],[],['army','socom','diu'],'Denver, CO','Public',
   'Forward-deployed engineer model. MBAs go to the Foundry/Gotham business side or Palantir Ventures.'],
  ['Shield AI','dtech',['autonomy'],['a16z','pt','rr'],['socom','af'],'San Diego, CA','Late',
   'Hivemind autonomy stack plus V-BAT airframe. Hardware + software, which makes ops roles unusually meaty.'],
  ['Applied Intuition','dtech',['autonomy'],['lux','gc','a16z'],['army','diu'],'Mountain View, CA','Late',
   'Crossed over from automotive AV tooling into defense ground autonomy. Strong MBA pipeline already.'],
  ['Scale AI','dtech',['autonomy','c2'],['a16z','fp'],['diu','af'],'San Francisco, CA','Late',
   'Data labeling and eval, now Thunderforge-style planning tools. The picks-and-shovels position.'],
  ['Vannevar Labs','dtech',['c2','ew'],['fp','8vc'],['socom','nro'],'Palo Alto, CA','Growth',
   'NLP over foreign-language open source for the IC. Small, senior, mission-forward team.'],
  ['Epirus','dtech',['cuas','ew'],['8vc','gc'],['army','navy'],'Torrance, CA','Growth',
   'High-power microwave for drone swarms. A bet that magazine depth beats missile-per-drone economics.'],
  ['Chaos Industries','dtech',['ew','cuas'],['a16z','8vc'],['af','navy'],'Los Angeles, CA','Growth',
   'Radar and sensing built like a software company. Rapid recent fundraising.'],
  ['Saronic','dtech',['maritime','autonomy'],['a16z','8vc','gc'],['navy','socom'],'Austin, TX','Growth',
   'Autonomous surface vessels. Riding the mass-attritable-hull thesis hard.'],
  ['Skydio','dtech',['autonomy','cuas'],['a16z','lux'],['army','diu'],'San Mateo, CA','Late',
   'Largest US drone maker; pivoted from consumer to defense and public safety. Battery and magnet supply chains are its exposure.'],
  ['Hadrian','dtech',['mfg'],['a16z','lux','fp'],['af'],'Torrance, CA','Growth',
   'Automated precision machining factories — attacking the supply-base bottleneck, not the platform. The template for the castings version of this idea.'],
  ['Castelion','dtech',['hyper'],['a16z','lux'],['army','af'],'El Segundo, CA','Early',
   'Low-cost strike missiles built SpaceX-style. Ex-SpaceX founding team.'],
  ['Ursa Major','dtech',['hyper','launch'],['8vc'],['af','navy'],'Berthoud, CO','Growth',
   'Merchant rocket and hypersonic propulsion — sells engines so primes do not have to build them. The clearest example of the merchant-supplier thesis.'],
  ['X-Bow Systems','dtech',['hyper'],[],['af','army'],'Albuquerque, NM','Growth',
   'Additively manufactured solid rocket motors. Attacks the cure-time and mandrel constraints that cap SRM output.'],
  ['True Anomaly','dtech',['space'],['8vc'],['sf','sda'],'Denver, CO','Growth',
   'Space domain awareness and on-orbit maneuver. Directly downstream of Space Force budget growth.'],
  ['IperionX','dtech',['mfg'],[],['af','navy'],'Charlotte, NC','Public',
   'Titanium from scrap and mineral feedstock via powder metallurgy. Received $47.1M from DoD toward a domestic mineral-to-metal titanium chain — the response to zero US sponge production.'],
  ['MP Materials','dtech',['mfg'],[],['af','army'],'Las Vegas, NV','Public',
   'Mountain Pass mine plus magnet manufacturing. DoD bought $400M of convertible preferred in 2025 and holds an effective ~15% stake with an NdPr price floor. The template for sovereign offtake structures.'],
  ['Noveon Magnetics','dtech',['mfg'],[],['army','af'],'San Marcos, TX','Growth',
   'The only operational US maker of sintered NdFeB magnets. Closed a $215M Series C in Jan 2026. Recycles end-of-life magnets as feedstock.'],
  ['Vulcan Elements','dtech',['mfg'],[],['army','af'],'Durham, NC','Growth',
   'Rare earth magnets; received a $620M loan from the Pentagon\'s Office of Strategic Capital in Nov 2025 — the largest OSC loan to date. ~10 t/yr capacity as of late 2025, scaling hard.'],
  ['Perpetua Resources','dtech',['mfg'],[],['army'],'Boise, ID','Public',
   'Stibnite project — gold plus the only meaningful US antimony resource. Antimony goes into primers and tracers; Chinese exports fell ~97%.'],
  ['Phoenix Tailings','dtech',['mfg'],['8vc'],['af'],'Woburn, MA','Growth',
   'Rare earth refining with no solvent extraction and near-zero waste. The permitting problem, not the chemistry problem, is what blocks US refineries.'],
  ['Niron Magnetics','dtech',['mfg'],[],['army','navy'],'Minneapolis, MN','Growth',
   'Iron-nitride permanent magnets — no rare earths at all. Substitution is the one lever export controls cannot reach.'],
  ['Kratos','dtech',['hyper','autonomy'],[],['af','navy'],'San Diego, CA','Public',
   'Target drones, jet-powered UAS, and now hypersonic test infrastructure — announced a mid-tier arc jet and laser facility in Odon, IN in May 2026.'],

  ['SpaceX','space',['launch','space'],['fp','sq'],['nro','sf','nasa'],'Hawthorne, CA','Late',
   'Starlink/Starshield make it the largest single node in the ecosystem. Few MBA-titled roles; entry is usually finance, Starlink business ops, or supply chain.'],
  ['Rocket Lab','space',['launch','space'],[],['sda','sf','nasa'],'Long Beach, CA','Public',
   'Electron/Neutron plus a fast-growing components business. Vertically integrating into spacecraft.'],
  ['Firefly Aerospace','space',['launch','space'],[],['sf','nasa'],'Cedar Park, TX','Public',
   'Alpha launch, Blue Ghost lunar lander, Elytra orbital vehicles.'],
  ['Stoke Space','space',['launch'],['fp'],['sf','nasa'],'Kent, WA','Growth',
   'Fully reusable second stage — the hardest unsolved problem in launch.'],
  ['Impulse Space','space',['space','hyper'],['fp','lux'],['sf','nasa'],'Redondo Beach, CA','Growth',
   'In-space transportation (Mira, Helios kick stage). Tom Mueller, ex-SpaceX propulsion.'],
  ['K2 Space','space',['space'],['fp','a16z'],['sda','sf'],'Torrance, CA','Growth',
   'Large, cheap satellite buses that assume abundant launch capacity.'],
  ['Varda Space','space',['space','mfg'],['fp','lux'],['af','nasa'],'El Segundo, CA','Growth',
   'In-space pharma manufacturing plus reentry capsules — and therefore a hypersonic test service as a side business.'],
  ['Muon Space','space',['space'],['gc','lux'],['sda','nasa'],'Mountain View, CA','Growth',
   'Turnkey LEO constellations for climate and defense sensing.'],
  ['Albedo','space',['space'],['8vc'],['nro','sf'],'Broomfield, CO','Early',
   'Very-low-orbit satellites for 10cm commercial imagery.'],
  ['Astranis','space',['space'],['a16z','fp'],['sf'],'San Francisco, CA','Late',
   'Small GEO comsats — a contrarian bet against LEO constellations.'],
  ['Hermeus','space',['hyper'],['8vc'],['af'],'Atlanta, GA','Growth',
   'Hypersonic aircraft, incrementally: Quarterhorse to Darkhorse. Constrained by the same test capacity everyone else is.'],
  ['Orbit Fab','space',['space','launch'],[],['sf','af'],'Lafayette, CO','Early',
   'In-space refueling — "gas stations in space." The classic chicken-and-egg: nobody launches refuelable satellites until fuel exists.'],

  ['a16z American Dynamism','investor',['autonomy','space','mfg','cuas'],[],[],'Menlo Park, CA','Fund',
   'Coined the category. The best single reading list for the thesis. Hosts a summit worth attending as a first-year.'],
  ['Founders Fund','investor',['space','autonomy','hyper'],[],[],'San Francisco, CA','Fund',
   'Earliest and most concentrated: SpaceX, Palantir, Anduril. Founder-first, contrarian, very large checks.'],
  ['Lux Capital','investor',['autonomy','space','mfg'],[],[],'New York, NY','Fund',
   'Deep-tech generalist with a strong defense book. Publishes unusually candid letters.'],
  ['8VC','investor',['maritime','ew','space'],[],[],'Austin, TX','Fund',
   'Joe Lonsdale; overlaps heavily with the Palantir alumni network.'],
  ['General Catalyst','investor',['autonomy','maritime','c2'],[],[],'Cambridge, MA','Fund',
   'Came late but aggressively, with a dedicated resilience practice.'],
  ['Shield Capital','investor',['autonomy','c2','ew'],[],[],'San Francisco, CA','Fund',
   'Early-stage, ex-operator and ex-government partners. Good for understanding acquisition mechanics.'],
  ['Decisive Point','investor',['c2','autonomy'],[],[],'Washington, DC','Fund',
   'DC-based, policy-literate seed fund. Useful if you want the Beltway view.'],
  ['In-Q-Tel','investor',['c2','ew','space'],[],[],'Arlington, VA','Strategic',
   'The IC\'s strategic investor. Not a return-maximizing fund — a technology-access one.'],
  ['Point72 Ventures','investor',['autonomy','space'],[],[],'Stamford, CT','Fund',
   'Crossover investor with a defense-tech vertical.'],
  ['Razor\'s Edge','investor',['autonomy','ew'],[],[],'Reston, VA','Fund',
   'National-security specialist; frequently the bridge round before a growth fund.'],
  ['Sequoia','investor',['space','c2'],[],[],'Menlo Park, CA','Fund',
   'Selective participation, usually at growth stage once contract revenue is visible.'],
  ['DoD Office of Strategic Capital','investor',['mfg'],[],[],'Arlington, VA','Strategic',
   'Makes loans, not grants, into supply-chain capital formation. Lent Vulcan Elements $620M in Nov 2025. The most underrated node on this map for anyone interested in industrial finance.'],

  ['DIU','gov',['autonomy','c2','space'],[],[],'Mountain View, CA','DoD',
   'Defense Innovation Unit — the commercial on-ramp. Runs HyCAT for airborne hypersonic test beds. Best single org to understand if you want to sell to DoD.'],
  ['SDA','gov',['space'],[],[],'Washington, DC','Space Force',
   'Space Development Agency — buys proliferated LEO tracking/transport layers on two-year tranches.'],
  ['AFWERX','gov',['autonomy','mfg','hyper'],[],[],'Dayton, OH','Air Force',
   'SBIR/STTR at scale. Where most small defense companies get their first dollar.'],
  ['SOCOM','gov',['autonomy','c2','ew'],[],[],'Tampa, FL','DoD',
   'Special Operations Command. Small budget, fast authority — the classic beachhead customer.'],
  ['DARPA','gov',['hyper','autonomy','ew'],[],[],'Arlington, VA','DoD',
   'Funds the science, not the fielding. Program manager tours are a real career move.'],
  ['NRO','gov',['space','ew'],[],[],'Chantilly, VA','IC',
   'National Reconnaissance Office; the largest classified space buyer.'],
  ['US Space Force','gov',['space','launch'],[],[],'Washington, DC','Service',
   'Newest service, fastest-growing budget line, most commercial-friendly acquisition posture.'],
  ['US Navy','gov',['maritime','cuas'],[],[],'Washington, DC','Service',
   'Shipbuilding backlog plus the unmanned surface vessel push. Castings and forgings are its hard constraint.'],
  ['US Army','gov',['cuas','autonomy','c2'],[],[],'Washington, DC','Service',
   'Largest force structure; counter-UAS and NGC2 are the live fights. Owns the ammunition plants, and therefore the energetics problem.'],
  ['US Air Force','gov',['hyper','cuas','autonomy'],[],[],'Washington, DC','Service',
   'CCA (collaborative combat aircraft) is the flagship autonomy program.'],
  ['NASA','gov',['launch','space'],[],[],'Washington, DC','Civil',
   'Not defense, but the same supplier base — and a softer first customer for space startups.'],
  ['IBAS','gov',['mfg'],[],[],'Washington, DC','DoD',
   'Industrial Base Analysis and Sustainment program. Names castings and forgings a priority sector. If you want to know what the Pentagon thinks is broken, read what IBAS funds.'],
];

const BUYER_ID = { af:'US Air Force', navy:'US Navy', army:'US Army', socom:'SOCOM',
  nro:'NRO', sda:'SDA', sf:'US Space Force', diu:'DIU', nasa:'NASA' };
// 'ex' is deliberately unmapped — it marks "there is a lead investor and we
// have not verified who." Holes are honest; invented edges are not.
const INV_ID = { a16z:'a16z American Dynamism', fp:'Founders Fund', lux:'Lux Capital',
  '8vc':'8VC', gc:'General Catalyst', sc:'Shield Capital', dp:'Decisive Point',
  iqt:'In-Q-Tel', pt:'Point72 Ventures', rr:'Razor\'s Edge', sq:'Sequoia',
  osc:'DoD Office of Strategic Capital' };

/* ─── 3. VALUE CHAIN ──────────────────────────────────────────────────
   Ten segments, raw inputs on the left, fielded capability on the right.
   `domestic` = analyst estimate of the share of US need that can be met
   from US or reliable allied sources. `risk` is the headline judgement.

   The story the numbers tell: value and US advantage concentrate on the
   RIGHT. Risk concentrates on the LEFT. The US is unbeatable at software
   and integration and dependent for the atoms those systems are made of.
   ─────────────────────────────────────────────────────────────────── */

const SEGMENTS = [
{ id:'raw', n:1, name:'Raw materials & critical minerals', short:'Raw materials',
  domestic:22, risk:'Critical',
  bind:'Foreign control', bindWhy:'Nine of the twenty-nine inputs below have been the subject of a Chinese export control action since 2023. No amount of US capital changes that on a short timescale.',
  what:'Mined and primary-produced inputs: titanium, rare earths, gallium, antimony, tungsten, cobalt, energetic precursors. Nothing downstream exists without these, and they are the least substitutable part of the chain.',
  why:'This is the segment an adversary can act on unilaterally, on a timescale of weeks, with a customs notice rather than a weapon. Nine of the twenty-nine inputs below have been the subject of a Chinese export control action since 2023.',
  verdict:'The worst-covered segment in the chain, and the one where a single policy change abroad moves the whole industry.',
  players:{ incumbents:['Materion','ATI','US Magnesium','Energy Fuels'],
    challengers:['MP Materials','IperionX','Perpetua Resources','Noveon Magnetics','Vulcan Elements','Phoenix Tailings','Niron Magnetics','NioCorp'],
    capital:['DoD Office of Strategic Capital','a16z American Dynamism','Lux Capital','EXIM Bank'],
    gov:['IBAS','Defense Logistics Agency','US Geological Survey','Dept of the Interior'] },
  chokepoints:[
  // ── the acute ones ──
  {k:'Titanium sponge', use:'Airframes, engine parts, submarine hulls', risk:'Critical', domestic:0,
   control:'Japan ~73%, Kazakhstan ~13%, Saudi Arabia ~13%',
   note:'The US produced ZERO titanium sponge in 2025 and is 100% import-reliant; dependence went from 68% in 2020 to 100% by 2023. Both main suppliers sit near Russia, China and North Korea. DoD put $47.1M into IperionX to rebuild a mineral-to-metal chain.',
   src:'USGS Mineral Commodity Summaries; Section 232 titanium sponge investigation'},
  {k:'Ammonium perchlorate', use:'Solid rocket motor oxidiser — every missile and SRM', risk:'Critical', domestic:100,
   control:'One US plant (AMPAC, Cedar City UT)',
   note:'THE most instructive row in this file: 100% domestic and still the highest-risk input in the chain, because there is exactly one supplier. A single point of failure that can throttle the entire propulsion ecosystem. The Army is actively expanding sources.',
   src:'Janes, "Rocket fuel: US Army expanding ammonium perchlorate sources"'},
  {k:'Samarium', use:'SmCo magnets — high-temperature actuators in missiles and aircraft', risk:'Critical', domestic:0,
   control:'China, effectively total',
   note:'Hit by China\'s April 2025 rare earth controls and added to the Jan 2026 export licensing catalogue. SmCo is used precisely where NdFeB fails on temperature, so substitution is hardest exactly where the need is most defense-specific.',
   src:'CSIS; China MOFCOM Jan 2026 Export Licensing Catalogue'},
  {k:'TNT', use:'Artillery and bomb fill', risk:'Critical', domestic:0,
   control:'Poland (Nitro-Chem) has been the DoD source',
   note:'No US producer since 1986. The Army has funded a new domestic plant in Kentucky, but until it runs, the most basic explosive in the inventory is imported from a single allied supplier.',
   src:'US Army contract announcements; congressional industrial base testimony'},
  {k:'Dysprosium & terbium', use:'Heavy rare earth dopants that keep magnets working hot', risk:'Critical', domestic:5,
   control:'China, near-total for separation',
   note:'Under China\'s April 2025 controls. Rare-earth customs enforcement cases in China rose from 91 to 317 during 2025. Lynas is standing up heavy separation in Texas; nothing is at scale yet.',
   src:'ORF America, "China\'s Critical Mineral Export Controls"'},
  {k:'Gallium', use:'GaN for AESA radar, electronic warfare, high-power RF', risk:'Critical', domestic:0,
   control:'China ~98% of primary production',
   note:'China banned exports to the US in Dec 2024, then SUSPENDED the ban until 27 Nov 2026 — but the licensing requirement stayed. Shipments to Japan have run at zero so far in 2026, which shows what the licence regime does even without a ban. Treat the suspension as a reprieve, not a resolution.',
   src:'The Oregon Group; Pillsbury, "China Suspends Export Controls"; Metal Tech News Mar 2026'},
  {k:'Germanium', use:'Infrared optics for thermal sights; satellite solar cells', risk:'Critical', domestic:5,
   control:'China dominant; same control regime as gallium',
   note:'Every thermal weapon sight and most space solar cells route through this. Same Dec 2024 ban, same suspension to Nov 2026, same surviving licence requirement.',
   src:'Pillsbury; ORF America'},
  {k:'Antimony', use:'Primers, tracers, hardened lead, flame retardants', risk:'Critical', domestic:5,
   control:'China, Russia, Tajikistan',
   note:'Chinese exports fell roughly 97% and antimony trioxide prices about doubled after the 2024 controls. Perpetua\'s Stibnite project in Idaho is the only meaningful US resource and is years from production.',
   src:'ORF America; CSIS'},
  {k:'Nitrocellulose', use:'Propellant for artillery and small arms', risk:'Critical', domestic:40,
   control:'Very thin US capacity; Radford AAP',
   note:'The binding constraint on 155mm shell output that got far less attention than the shells themselves. Energetic parts and propellants can take a year to source.',
   src:'Breaking Defense, "a perilous crunch in the supply chain" (Jan 2026)'},
  {k:'NdPr oxide / metal', use:'Permanent magnets in every actuator, motor and servo', risk:'High', domestic:15,
   control:'China ~90% of separation and magnet making',
   note:'The one input where US policy has actually moved: DoD took $400M of MP Materials convertible preferred plus warrants for an effective ~15% stake, with a price floor on NdPr. Magnet output starts H2 2026, reaching ~10,000 t once the new plant commissions around 2028.',
   src:'MP Materials; FAS, "Unpacking the DoD and MP Partnership"'},
  {k:'Tungsten', use:'Kinetic penetrators, machine tooling, armour', risk:'High', domestic:10,
   control:'China; only 15 firms whitelisted to export for 2026–27',
   note:'The whitelist mechanism matters more than any tariff: Beijing now picks the exporters first, then manages volume and timing. Almonty\'s Sangdong mine in Korea is the main non-Chinese answer.',
   src:'Rare Earth Exchanges, "China\'s Exclusive Export List 2026-2027"'},
  {k:'Graphite (anode grade)', use:'Batteries for UAS, subs, directed energy', risk:'High', domestic:5,
   control:'China ~95% of anode material',
   note:'Under Chinese export permitting since Dec 2023. Every small drone program inherits this exposure and almost none of them model it.',
   src:'ORF America'},
  {k:'Rhenium', use:'Single-crystal turbine blades (2–6% of the alloy)', risk:'High', domestic:15,
   control:'Chile, Kazakhstan; a molybdenum by-product',
   note:'You cannot open a rhenium mine — it only exists as a by-product, so supply does not respond to price. That makes recovery from retired blades the only real lever.',
   src:'USGS Mineral Commodity Summaries'},
  {k:'Cobalt', use:'Superalloy binder, batteries', risk:'High', domestic:10,
   control:'DRC mining, China refining',
   note:'Two separate risks stacked: where it comes out of the ground and where it gets refined are different countries, and both are problems.',
   src:'USGS'},
  {k:'Magnesium', use:'Castings, aluminium alloying', risk:'High', domestic:10,
   control:'China ~85%+ of primary production',
   note:'US Magnesium in Utah is the sole domestic producer and has declared force majeure before, which briefly threatened North American aluminium alloying.',
   src:'USGS'},
  {k:'HALEU / naval-grade uranium', use:'Naval reactors, space nuclear propulsion', risk:'High', domestic:25,
   control:'Russian LEU import ban since 2024; enrichment capacity thin',
   note:'Centrus and Orano are scaling; the constraint is enrichment capacity, which takes years and a licence, not months and a cheque.',
   src:'DOE; Prohibiting Russian Uranium Imports Act'},
  {k:'RDX / HMX', use:'High explosive fill for warheads', risk:'High', domestic:60,
   control:'Holston AAP (BAE-operated); expansion underway',
   note:'Government-owned, contractor-operated. Capacity is being expanded but the plants are old and the permitting for new energetics capacity is brutal.',
   src:'US Army; BAE Systems'},
  {k:'HTPB binder', use:'Solid rocket motor fuel binder', risk:'High', domestic:50,
   control:'A handful of qualified producers',
   note:'Qualification, not chemistry, is the moat — a new binder means requalifying every motor that uses it.',
   src:'Breaking Defense (Jan 2026)'},
  {k:'Hafnium', use:'Superalloys, nuclear control rods', risk:'Medium', domestic:30,
   control:'By-product of zirconium refining; France, US',
   note:'Same by-product logic as rhenium: supply is set by someone else\'s production decisions.', src:'USGS'},
  {k:'Tantalum', use:'Capacitors in essentially all avionics', risk:'Medium', domestic:10,
   control:'DRC/Rwanda mining, China processing', note:'Small volumes, high criticality, and a conflict-minerals compliance burden on top.', src:'USGS'},
  {k:'Carbon fibre (aerospace grade)', use:'Airframes, motor cases, pressure vessels', risk:'Medium', domestic:40,
   control:'Toray, Hexcel, Mitsubishi; PAN precursor Japan-heavy',
   note:'Hexcel gives real US capacity, but the precursor and the qualification pedigree are concentrated. Switching suppliers means requalifying the part.', src:'Company filings'},
  {k:'Lithium', use:'UAS and soldier-power batteries', risk:'Medium', domestic:20,
   control:'Chile/Australia mining, China refining', note:'Refining is the chokepoint, not the resource — the standard pattern for almost everything on this list.', src:'USGS'},
  {k:'Helium', use:'Launch vehicle pressurisation, leak testing', risk:'Medium', domestic:60,
   control:'Qatar, Algeria, Russia, US private production',
   note:'The Federal Helium Reserve was divested in 2024, so the government no longer holds a buffer. Every launch scrub for a helium leak is a reminder that this is a consumable nobody hedges.', src:'BLM; USGS'},
  {k:'Zirconium', use:'Alloys, nuclear, ceramics', risk:'Medium', domestic:50, control:'Australia, South Africa',
   note:'Reasonably diversified and allied-sourced.', src:'USGS'},
  {k:'Silver', use:'Electrical contacts, brazing alloys, solar', risk:'Medium', domestic:35,
   control:'Diversified mining; 44 Chinese firms whitelisted for export',
   note:'Newly added to China\'s Jan 2026 licensing catalogue, which is the more interesting fact than the price — it signals the whitelist model spreading to commodity metals.',
   src:'China MOFCOM Jan 2026 catalogue; Discovery Alert'},
  {k:'Niobium', use:'Superalloys, high-strength steel', risk:'Medium', domestic:0,
   control:'Brazil (CBMM) ~80–85% of world supply',
   note:'Extreme single-country concentration, but the country is friendly. A useful contrast with the Chinese-controlled inputs: concentration and risk are not the same thing.', src:'USGS'},
  // ── the good news, which matters just as much ──
  {k:'Beryllium', use:'Optics, mirrors, structures, X-ray windows', risk:'Low', domestic:90,
   control:'Materion, Spor Mountain UT — a US near-monopoly',
   note:'The one where America holds the chokepoint. Worth studying as the counter-example: domestic resource plus a single vertically integrated producer plus decades of qualification.', src:'USGS; Materion'},
  {k:'Aluminium & Al-Li plate', use:'Airframes, structures', risk:'Low', domestic:85,
   control:'Arconic, Kaiser, Constellium',
   note:'Bauxite is imported but fungible and globally traded, and US rolling and plate capacity is real. Not a problem.', src:'USGS'},
  {k:'Specialty steel & armour plate', use:'Hulls, armour, tooling', risk:'Low', domestic:90,
   control:'Domestic mills (Nucor, Cleveland-Cliffs, ATI)',
   note:'Genuinely fine. Worth saying out loud, because a map where everything is red teaches nothing.', src:'USGS; company filings'},
  ],
  whitespace:[
  {t:'Magnet-to-magnet recycling at industrial scale', heat:'Hot', kind:'Company',
   d:'The largest untapped US rare earth "deposit" is the magnets already inside American scrap — motors, hard drives, EVs, retired aircraft. Noveon already feeds on recycled material. Nobody has built the collection and sortation layer underneath it, which is a logistics business, not a chemistry one.'},
  {t:'Rare-earth-free motor and actuator design', heat:'Contrarian', kind:'Company',
   d:'Substitution is the only lever an export control cannot reach. Iron-nitride (Niron), ferrite plus smarter power electronics, switched-reluctance topologies. The prize is not matching NdFeB — it is being good enough at 40% of the performance in the 70% of applications that are over-specified.'},
  {t:'Sovereign offtake insurance, productised', heat:'Contrarian', kind:'Policy / Fintech',
   d:'The MP Materials deal works because DoD guaranteed an NdPr price floor. The binding constraint on Western mining is not geology, it is price risk — nobody finances a mine China can bankrupt by dumping. Take that floor structure and make it a repeatable instrument across twenty materials. This is the single highest-leverage idea on the page and it is a finance product, not a technology.'},
  {t:'Waste-stream feedstock: coal ash, phosphogypsum, acid mine drainage', heat:'Early', kind:'Company',
   d:'Rare earths already sit in permitted, characterised, on-US-soil waste piles. The mining is done. You skip the decade of permitting that kills every greenfield project, and you get paid to remediate.'},
  {t:'By-product recovery as a business model', heat:'Early', kind:'Company',
   d:'Rhenium, hafnium, gallium, germanium and tellurium have no mines of their own — they are by-products, so supply cannot respond to price. Buying the right to extract them from someone else\'s existing process stream is a capital-light position in a market with no supply elasticity.'},
  {t:'Strategic stockpile-as-a-service', heat:'Early', kind:'Company',
   d:'Primes cannot justify holding 18 months of gallium on their balance sheet; the government stockpile is slow and political. A bonded private warehouse selling hedged, ITAR-compliant inventory access is a boring, financeable business that did not need to exist before 2023.'},
  ] },

{ id:'refine', n:2, name:'Refining, separation & specialty alloys', short:'Refining',
  domestic:30, risk:'Critical',
  bind:'Process capacity', bindWhy:'The US has the ore and lacks the plants. The chemistry is a century old; the permit takes a decade. This is a domestic blocker wearing a foreign costume.',
  what:'Turning ore and scrap into usable metal: rare earth separation, titanium sponge and powder, superalloy melting, magnet sintering.',
  why:'Almost every "China dominates X" statistic is really about this segment, not mining. The US has resources; it has very little capacity to turn them into metal.',
  verdict:'The real chokepoint, and the one most often mistaken for a mining problem. Fixing mining without fixing separation just exports concentrate to China and buys it back.',
  players:{ incumbents:['ATI','Carpenter Technology','Materion','Howmet Aerospace'],
    challengers:['MP Materials','Noveon Magnetics','Vulcan Elements','Phoenix Tailings','IperionX','Lynas USA','Energy Fuels'],
    capital:['DoD Office of Strategic Capital','EXIM Bank','a16z American Dynamism'],
    gov:['IBAS','Dept of Energy','Defense Logistics Agency'] },
  chokepoints:[
  {k:'Heavy rare earth separation', use:'Dy, Tb, Sm for high-temp magnets', risk:'Critical', domestic:5,
   control:'China, near-total', note:'Light separation is being solved at Mountain Pass. Heavies are far harder chemistry and essentially absent from the US. Lynas is building in Texas.', src:'FAS; Lynas'},
  {k:'Titanium sponge & powder', use:'Feedstock for every Ti part', risk:'Critical', domestic:0,
   control:'Zero US sponge capacity since the last plant closed', note:'IperionX\'s powder-metallurgy route tries to skip sponge entirely by going scrap-to-powder. If it works it is a genuine leapfrog rather than a restoration.', src:'USGS; DoD award'},
  {k:'NdFeB magnet sintering', use:'Finished magnets', risk:'High', domestic:10,
   control:'China >90% of global magnet manufacturing', note:'Noveon is the only operational US sintered NdFeB maker; Vulcan was at ~10 t/yr in late 2025 against a US need in the thousands of tonnes. The gap is two orders of magnitude and closing fast on paper, slowly in physical reality.', src:'The Wire China; MP Materials'},
  {k:'Solvent extraction permitting', use:'Any conventional REE refinery', risk:'High', domestic:30,
   control:'US environmental permitting timelines', note:'Not a foreign problem at all — a domestic one. The chemistry is a century old; the permit is what takes a decade. This is why non-solvent routes are interesting.', src:'Columbia CGEP'},
  {k:'Superalloy vacuum melting capacity', use:'Turbine-grade nickel alloys', risk:'High', domestic:55,
   control:'A handful of VIM/VAR furnaces', note:'Highly concentrated, capital-intensive, and now competing with commercial aero demand that is itself rising sharply.', src:'Deloitte A&D Outlook 2026'},
  {k:'Gallium & germanium refining', use:'GaN, IR optics', risk:'Critical', domestic:5,
   control:'China ~98% of gallium', note:'Both are by-products of aluminium and zinc processing — the US throws away feedstock it could recover, because at Chinese prices recovery never penciled. Controls change that math.', src:'ORF America'},
  ],
  whitespace:[
  {t:'Separation without solvent extraction', heat:'Hot', kind:'Company',
   d:'Phoenix Tailings and others are chasing electrochemical and selective-ligand routes with near-zero waste. The insight is that the blocker on a US refinery is the permit, so the winning technology is whichever one is easiest to permit — not whichever is cheapest at steady state.'},
  {t:'Containerised modular refineries at the mine mouth', heat:'Early', kind:'Company',
   d:'Ship the plant to the ore instead of the ore to the plant. Smaller units permit faster, finance as equipment rather than infrastructure, and let you serve deposits too small for a conventional refinery.'},
  {t:'Allied tolling network as a treaty instrument', heat:'Contrarian', kind:'Policy',
   d:'The US does not have to do separation domestically to be secure — it has to do it somewhere China cannot switch off. A formal tolling arrangement across Japan, Australia, Estonia and Malaysia is years faster than a domestic plant and nobody is negotiating it as a single package.'},
  {t:'Closed-loop superalloy recovery', heat:'Early', kind:'Company',
   d:'Rhenium, hafnium and cobalt in a retired turbine blade are worth more than in the ground and are already inside the fence at a US depot. Keeping them in a closed industrial loop is cheaper than mining and fully domestic by construction.'},
  {t:'Qualification-as-a-service for new material sources', heat:'Early', kind:'Company',
   d:'A new supplier is worthless until the alloy is qualified against the spec, which takes years of coupon testing nobody wants to pay for. A shared qualification body — funded once, usable by all primes — would unlock more supply than any single mine.'},
  ] },

{ id:'energetics', n:3, name:'Energetics & propellants', short:'Energetics',
  domestic:45, risk:'Critical',
  bind:'Single supplier', bindWhy:'One ammonium perchlorate plant. One foreign TNT source. Two solid rocket motor houses. Every acute problem here is a supplier-count problem.',
  what:'Explosives, propellants, oxidisers, binders and the plants that make them: AP, TNT, RDX/HMX, nitrocellulose, HTPB.',
  why:'Munitions output is capped here, not at final assembly. Energetic parts and propellants can take a year to source, and it is the segment where "just build another factory" collides hardest with permitting and insurance.',
  verdict:'The segment with the widest gap between political urgency and physical capacity. Also the one where a single new entrant can move a national number.',
  players:{ incumbents:['BAE Systems Inc','Northrop Grumman','L3Harris','AMPAC'],
    challengers:['X-Bow Systems','Anduril','Ursa Major','Castelion'],
    capital:['a16z American Dynamism','Lux Capital','Founders Fund','DoD Office of Strategic Capital'],
    gov:['US Army','IBAS','AFWERX'] },
  chokepoints:[
  {k:'Ammonium perchlorate — single source', use:'Every solid rocket motor', risk:'Critical', domestic:100,
   control:'AMPAC, Cedar City UT — sole US producer', note:'The quiet chokepoint that can throttle the entire propulsion ecosystem. 100% domestic and maximum risk, which is the whole lesson of this view.', src:'Janes; National Interest'},
  {k:'TNT', use:'Artillery and bomb fill', risk:'Critical', domestic:0, control:'Imported, Poland',
   note:'No domestic production since 1986. A new plant is funded and not yet running.', src:'US Army'},
  {k:'Nitrocellulose', use:'Gun propellant', risk:'Critical', domestic:40, control:'Radford AAP, thin commercial base',
   note:'The real cap on 155mm output during the Ukraine surge.', src:'Breaking Defense'},
  {k:'Solid rocket motor capacity', use:'Missiles, interceptors, boosters', risk:'Critical', domestic:75,
   control:'Northrop Grumman and L3Harris/Aerojet, effectively a duopoly',
   note:'The Pentagon made a rare ~$1B direct investment tied to L3Harris\'s rocket motor business in Jan 2026 to secure propulsion for Tomahawk and Patriot. When the government has to buy into a supplier to keep it viable, that is the definition of a broken market structure.', src:'Breaking Defense; Defense News (Aug 2026)'},
  {k:'Energetics permitting & insurance', use:'Any new plant', risk:'High', domestic:40,
   control:'ATF, EPA, state siting, and the insurance market',
   note:'Under-discussed and often decisive: you can raise the capital for an energetics plant far faster than you can get it insured and sited.', src:'Industry reporting'},
  {k:'Perchlorate precursors', use:'AP feedstock', risk:'High', domestic:50, control:'Sodium perchlorate supply, China-linked',
   note:'In 2025 over 1,000 tonnes of Chinese sodium perchlorate was reportedly intercepted en route to Iran — a reminder that this precursor trade is both strategic and loosely policed.', src:'Open-source reporting cited in Janes'},
  ],
  whitespace:[
  {t:'Continuous-flow energetics manufacturing', heat:'Hot', kind:'Company',
   d:'Energetics are still made in batches, in big buildings, because that is how it was done in 1943. Continuous-flow microreactors hold milligrams in reaction at any instant instead of tonnes — which changes the hazard class, and therefore the siting, the insurance and the permit. It is the one idea that could actually multiply US energetics capacity this decade, and it is a chemical engineering business rather than a defense one.'},
  {t:'Additively manufactured motor grains', heat:'Hot', kind:'Company',
   d:'X-Bow and Anduril (via Adranos) print propellant grains instead of casting and curing them around a mandrel. Cure time and mandrel tooling are what cap SRM throughput, so this attacks the actual constraint rather than adding another traditional line.'},
  {t:'Perchlorate-free and halogen-free oxidisers', heat:'Early', kind:'Research',
   d:'SERDP has funded work on high-energy-density oxidisers without perchlorate. Getting there removes the single-supplier AP problem by removing AP, and removes a groundwater liability that constrains where you can test.'},
  {t:'Merchant energetics: sell propellant, not missiles', heat:'Contrarian', kind:'Company',
   d:'Ursa Major proved primes will buy propulsion rather than build it. Extend the model one step upstream and sell qualified energetic subassemblies to everyone — including the primes you would otherwise compete with. Lower margin, far wider moat, and it fixes a national problem as a side effect.'},
  {t:'Demilitarisation as feedstock', heat:'Early', kind:'Company',
   d:'The US pays to destroy expiring munitions that contain exactly the RDX, HMX and AP it is short of. Recovering and requalifying that fill turns a disposal cost line into a supply line.'},
  ] },

{ id:'micro', n:4, name:'Microelectronics, RF & sensing', short:'Microelectronics',
  domestic:40, risk:'High',
  bind:'Foreign control', bindWhy:'You can own the fab and still be dependent, because ~98% of primary gallium comes from China. Feedstock, not fabrication, is the exposure.',
  what:'Radiation-hardened and trusted silicon, GaN-on-SiC for radar and EW, infrared focal planes, inertial sensors, FPGAs.',
  why:'Defense needs small volumes of old nodes and exotic compounds — exactly what commercial fabs least want to make. The CHIPS build-out barely touches this.',
  verdict:'Improving at the leading edge and neglected in the long tail. The trusted-supply problem for small programs is worse than the headline fab numbers suggest.',
  players:{ incumbents:['RTX','BAE Systems Inc','L3Harris','Northrop Grumman','Texas Instruments'],
    challengers:['Chaos Industries','Epirus','Anduril'],
    capital:['In-Q-Tel','Shield Capital','Point72 Ventures','8VC'],
    gov:['DARPA','NRO','US Air Force','DIU'] },
  chokepoints:[
  {k:'Gallium feedstock for GaN', use:'AESA radar, EW, high-power RF', risk:'Critical', domestic:0,
   control:'China ~98% of primary gallium', note:'You can have a domestic GaN fab and still be dependent, because the metal going into the wafer is imported. Fab sovereignty without feedstock sovereignty is theatre.', src:'ORF America'},
  {k:'Rad-hard microelectronics', use:'Satellites, strategic systems', risk:'High', domestic:50,
   control:'A few trusted foundries, legacy nodes', note:'Small volumes, old processes, enormous qualification cost. Commercially unattractive by construction, which is why it stays fragile.', src:'DoD Trusted Foundry program'},
  {k:'IR focal plane arrays', use:'Thermal sights, missile seekers', risk:'High', domestic:45,
   control:'Germanium and specialty substrate supply', note:'Constrained by both the substrate material and a very thin set of qualified producers.', src:'USGS; industry'},
  {k:'Legacy-node supply for sustainment', use:'Keeping fielded systems alive', risk:'High', domestic:35,
   control:'Obsolete parts, grey market', note:'When a 1990s part goes end-of-life, programs buy from brokers with no provenance. This is a live counterfeit-parts problem, not a hypothetical one.', src:'GAO reporting'},
  {k:'Advanced packaging & test', use:'Everything', risk:'Medium', domestic:30,
   control:'Concentrated in Asia', note:'Even domestically fabbed wafers often leave the country to be packaged, which quietly undoes part of the point.', src:'Industry'},
  {k:'Inertial & atomic sensing', use:'Navigation without GPS', risk:'Medium', domestic:70,
   control:'Reasonable US base', note:'Actually a relative strength, and strategically vital as GPS denial becomes the default assumption.', src:'Industry'},
  ],
  whitespace:[
  {t:'Rad-hard by architecture, not by process', heat:'Contrarian', kind:'Company',
   d:'Space startups already fly commercial silicon with redundancy and shielding, and accept a shorter life. The traditional acquisition system still pays 100x for rad-hard-by-process parts. Whoever makes the architectural approach formally certifiable collapses a cost structure the primes depend on.'},
  {t:'Gallium and germanium recovery from domestic smelters', heat:'Hot', kind:'Company',
   d:'Both are by-products of aluminium and zinc processing that US operators currently discard because recovery never penciled against Chinese prices. Export controls changed the arithmetic, and the feedstock is already inside existing US plants.'},
  {t:'Trusted foundry as a service for the long tail', heat:'Early', kind:'Company',
   d:'Big programs get trusted access. The hundreds of small programs and SBIR-funded systems do not, and improvise. An aggregator that pools small orders into qualified runs serves a real, unserved, and growing market.'},
  {t:'On-die provenance and counterfeit attestation', heat:'Early', kind:'Company',
   d:'The grey market for obsolete defense parts is large and essentially unpoliced. Cryptographic attestation or physical marking at manufacture, checked at depot, is a modest technical problem and a serious unaddressed vulnerability.'},
  {t:'Defense chiplets', heat:'Early', kind:'Research',
   d:'Instead of one bespoke ASIC per program at enormous NRE, assemble qualified chiplets from a catalogue. Amortises qualification across programs — which is the actual cost driver in defense microelectronics.'},
  ] },

{ id:'forge', n:5, name:'Forgings, castings & precision machining', short:'Forgings & castings',
  domestic:55, risk:'High',
  bind:'Process capacity', bindWhy:'Not a shortage of orders — a shortage of presses, furnaces, qualified shops and machinists. The queue is the product.',
  what:'Large forgings, investment castings, single-crystal turbine blades, precision machined parts, fasteners, bearings.',
  why:'The Pentagon\'s own Industrial Base Analysis and Sustainment program names castings and forgings a priority sector. Lead times stretch because of stacked process queues, not a lack of orders.',
  verdict:'The quiet gating item on aircraft, missiles, munitions, satellites and ships simultaneously. America does not have a shortage of engine orders; it has a shortage of mission-critical process capacity.',
  players:{ incumbents:['Howmet Aerospace','Precision Castparts','ATI','Carpenter Technology','GE Aerospace'],
    challengers:['Hadrian','IperionX','Divergent Technologies','Velo3D'],
    capital:['a16z American Dynamism','Lux Capital','Founders Fund','private equity roll-ups'],
    gov:['IBAS','US Navy','US Air Force'] },
  chokepoints:[
  {k:'Large open-die forgings', use:'Landing gear, shafts, pressure hulls, rotors', risk:'High', domestic:50,
   control:'Very few large presses in the US', note:'You cannot buy a 50,000-tonne press quickly at any price. The asset base is decades old and the queue is the product.', src:'Greenwich Capital Group; PwC'},
  {k:'Investment castings — airfoils', use:'Turbine blades and vanes', risk:'High', domestic:55,
   control:'Concentrated foundries; GE sees airfoil demand +30% by 2030',
   note:'Casting remains the most persistent supply chain bottleneck. Commercial aero recovery and defense ramp hit the same foundries at the same time, and the foundries cannot serve both.', src:'Greenwich Capital Group; Deloitte'},
  {k:'Single-crystal blade capability', use:'Hot-section turbine parts', risk:'High', domestic:50,
   control:'A handful of qualified lines worldwide', note:'Extreme process know-how, low yield, and rhenium-dependent alloys. Hard to stand up from scratch even with unlimited money.', src:'Industry'},
  {k:'Aerospace-grade bearings', use:'Engines, actuators, gearboxes', risk:'Medium', domestic:45,
   control:'Thin domestic base, European and Japanese suppliers', note:'A classic hidden single-source risk that shows up in no headline.', src:'Industry'},
  {k:'Skilled machinists & welders', use:'All of the above', risk:'High', domestic:60,
   control:'Demographics', note:'The constraint no amount of capital fixes on a program timescale. It is why Hadrian\'s automation thesis attracted the funding it did.', src:'Oliver Wyman; Deloitte'},
  {k:'Qualified ITAR shop capacity', use:'Everything', risk:'Medium', domestic:65,
   control:'Fragmented, opaque', note:'Many qualified shops run well below capacity while programs wait months — because there is no market mechanism to find the slack.', src:'Industry'},
  ],
  whitespace:[
  {t:'Large-format additive as a forging substitute', heat:'Hot', kind:'Company',
   d:'For low-rate and spares, printing a near-net shape avoids the press queue entirely. The bottleneck is not the machine, it is the wait — so the winning pitch is lead time, not unit cost, which is a different sales motion than most AM companies run.'},
  {t:'Foundry roll-up plus automation', heat:'Hot', kind:'Company',
   d:'Hadrian did this for machining. Nobody has done it for casting, which IBAS names as a priority sector and which is more fragmented, more capital-starved, and full of retiring owners with no succession plan. This is the most obvious unexploited private-equity-meets-deep-tech play in the chain.'},
  {t:'A capacity marketplace for qualified shops', heat:'Contrarian', kind:'Company',
   d:'Match programs waiting on parts to AS9100/NADCAP shops sitting at 60% utilisation. Pure software against a physical problem, which is unusual in this segment. The hard part is trust and ITAR compliance, not the matching — which is exactly what makes it defensible.'},
  {t:'Cold spray and friction-stir repair at the depot', heat:'Early', kind:'Company',
   d:'Repairing a part is not a new part in the casting queue. Depot-level restoration converts a supply problem into a maintenance capability, and the Navy in particular has enormous latent demand.'},
  {t:'Qualification-as-a-service', heat:'Early', kind:'Company',
   d:'The moat in this segment is the AS9100/NADCAP paperwork, not the metallurgy. A firm that takes a competent general machine shop to defense-qualified in months rather than years expands the supplier base without building a single new machine.'},
  ] },

{ id:'prop', n:6, name:'Propulsion & rocket motors', short:'Propulsion',
  domestic:70, risk:'High',
  bind:'Single supplier', bindWhy:'A solid motor duopoly the Pentagon had to buy into to keep viable. Market structure, not engineering, is the constraint.',
  what:'Jet engines, solid and liquid rocket motors, hypersonic propulsion, electric and hybrid cycles.',
  why:'Structurally a duopoly in solid motors and a near-duopoly in large turbines. Concentration here propagates to every platform above it.',
  verdict:'Improving faster than any other constrained segment, because new entrants found a wedge — selling engines to platform builders instead of competing with them.',
  players:{ incumbents:['Northrop Grumman','L3Harris','GE Aerospace','RTX (Pratt)'],
    challengers:['Ursa Major','X-Bow Systems','Castelion','Anduril','Stoke Space','Impulse Space','Hermeus'],
    capital:['Founders Fund','a16z American Dynamism','8VC','Lux Capital'],
    gov:['US Air Force','US Navy','DIU','AFWERX'] },
  chokepoints:[
  {k:'Solid rocket motor duopoly', use:'All missiles and interceptors', risk:'Critical', domestic:75,
   control:'Northrop Grumman, L3Harris/Aerojet', note:'The Pentagon\'s ~$1B direct investment into L3Harris\'s motor business in Jan 2026 is the clearest possible signal that two suppliers is not enough.', src:'Breaking Defense (Jan 2026)'},
  {k:'Large turbine hot section', use:'Fighter and transport engines', risk:'High', domestic:65,
   control:'GE and Pratt; castings-limited', note:'Constrained by segment 5, not by engine design. The queue is in the foundry.', src:'Deloitte'},
  {k:'Hypersonic propulsion maturity', use:'Scramjets, boost-glide', risk:'High', domestic:70,
   control:'Few flight-qualified designs', note:'Held back as much by test capacity (segment 10) as by engineering.', src:'Air & Space Forces Magazine'},
  {k:'Motor case composites', use:'SRM structures', risk:'Medium', domestic:50,
   control:'Carbon fibre qualification', note:'Inherits the precursor concentration from segment 1.', src:'Industry'},
  {k:'Test stands for propulsion', use:'Qualifying any new motor', risk:'High', domestic:55,
   control:'Limited, aging, oversubscribed', note:'A new entrant can raise money faster than it can book stand time.', src:'Industry'},
  ],
  whitespace:[
  {t:'Merchant propulsion at scale', heat:'Hot', kind:'Company',
   d:'Ursa Major\'s model — sell engines so primes need not build them — is validated and nowhere near saturated. Every new missile and drone startup needs propulsion and none should build it. The wedge works because you are not threatening the prime, you are de-risking them.'},
  {t:'Deliberate third and fourth SRM sources', heat:'Hot', kind:'Company',
   d:'The government is now willing to co-invest capital directly, as the L3Harris deal shows. That materially changes the financeability of a new motor plant — the customer will fund the capex. Few founders have internalised how much that changes the risk profile.'},
  {t:'Propulsion that avoids exotic materials by design', heat:'Contrarian', kind:'Research',
   d:'Electric-pump-fed and hybrid cycles trade performance for supply chain simplicity. For attritable systems, where cost and buildability beat specific impulse, that trade is obviously right and almost nobody is optimising for it explicitly.'},
  {t:'Motor life extension and re-cast', heat:'Early', kind:'Company',
   d:'Large inventories of aging motors are approaching end of certified life. Re-certifying or re-casting them is far cheaper than new production and adds magazine depth without a new factory.'},
  {t:'Propulsion test-as-a-service', heat:'Early', kind:'Company',
   d:'Commercial test stands sold by the hour. The demand is visible in every new entrant\'s schedule slip, and unlike the motors themselves this is a real-estate-and-instrumentation business.'},
  ] },

{ id:'platform', n:7, name:'Structures, platforms & integration', short:'Platforms',
  domestic:85, risk:'Low',
  bind:'Process capacity', bindWhy:'Two submarine yards, a thin surface base, and a labour pool that cannot be conjured. Capability is not the issue; throughput is.',
  what:'Airframes, hulls, satellites buses, ground vehicles, and the systems integration that turns subsystems into a fielded platform.',
  why:'Where the primes earn their margin and where the US genuinely leads. Constrained from below by segments 1–6 rather than by its own capability.',
  verdict:'Well covered on capability, exposed on throughput. The interesting question here is not whether the US can build platforms but whether it can build cheap ones in quantity.',
  players:{ incumbents:['Lockheed Martin','Northrop Grumman','Boeing Defense','General Dynamics','RTX'],
    challengers:['Anduril','Saronic','Skydio','Castelion','K2 Space','Kratos'],
    capital:['Founders Fund','a16z American Dynamism','General Catalyst','8VC'],
    gov:['US Air Force','US Navy','US Army','DIU'] },
  chokepoints:[
  {k:'Shipbuilding capacity', use:'Surface combatants, submarines', risk:'Critical', domestic:85,
   control:'Two submarine yards; a thin surface base', note:'Domestic by law and constrained by labour, castings and dry-dock space. The most acute throughput problem in the entire chain, and the hardest to fix with capital.', src:'Oliver Wyman; congressional testimony'},
  {k:'Attritable-cost platform design', use:'Mass drone and munition programs', risk:'High', domestic:80,
   control:'Cost culture, not capability', note:'The US can build exquisite things. Building deliberately cheap things is a different discipline and the incumbent base is structurally bad at it.', src:'Industry'},
  {k:'Open architecture adoption', use:'Upgradeability, competition', risk:'Medium', domestic:75,
   control:'Prime incentives run the other way', note:'Closed interfaces are how incumbents retain aftermarket margin, so MOSA mandates keep getting diluted in practice.', src:'GAO; DoD MOSA policy'},
  {k:'Final assembly throughput', use:'All platforms', risk:'Medium', domestic:85,
   control:'Skilled labour and part availability', note:'Rarely the binding constraint — it is usually waiting on segment 5.', src:'Deloitte'},
  {k:'Non-traditional manufacturing entrants', use:'Volume production', risk:'Low', domestic:80,
   control:'Qualification barriers', note:'Auto and RV plants could plausibly build attritable hardware. Qualification, not capability, keeps them out.', src:'Industry'},
  ],
  whitespace:[
  {t:'The "kit prime": government-owned interfaces', heat:'Contrarian', kind:'Policy',
   d:'If the government owns the interface specification rather than the platform, it can recompete every subsystem every cycle. This is the single largest structural change available to defense acquisition, and it is opposed by exactly the firms best placed to implement it — which is why it needs a new kind of company to champion it.'},
  {t:'Cost-target-first platform design', heat:'Hot', kind:'Company',
   d:'Castelion and Saronic both start from a unit cost and design backwards. Inverting the normal requirements process is a cultural innovation, not a technical one, and it is the most transferable idea in modern defense tech.'},
  {t:'Non-traditional integrators', heat:'Contrarian', kind:'Company',
   d:'Recruit an RV plant, a boat builder, or an auto tier-1 into defense volume production. They already know how to make 10,000 of something, which is precisely the skill the defense base lacks. The business is the qualification bridge, not the manufacturing.'},
  {t:'Insurance and warranty products for attritable systems', heat:'Early', kind:'Fintech',
   d:'Nobody has worked out how to price, insure or account for hardware that is meant to be expended. Until that exists, program offices will keep over-specifying for survivability because the financial machinery assumes assets are recoverable.'},
  {t:'Shipyard-adjacent modular fabrication', heat:'Early', kind:'Company',
   d:'Build hull sections off-site in a factory and ship them to the yard. Standard practice in commercial shipbuilding in Korea, barely used in US naval construction, and it decouples output from dry-dock availability.'},
  ] },

{ id:'software', n:8, name:'Software, autonomy & C2', short:'Software & autonomy',
  domestic:95, risk:'Low',
  bind:'Institutional', bindWhy:'The algorithms work. There is no accepted method to certify that an autonomous system is safe to field, and no accreditation timeline that matches weekly iteration. The blocker is a process nobody owns.',
  what:'Autonomy stacks, mission planning, command and control, data fusion, simulation, model training and evaluation.',
  why:'The segment where the US holds an unambiguous and probably durable lead, and where marginal cost is near zero rather than set by a foundry queue.',
  verdict:'Best-covered segment in the chain by a wide margin. The gap is not capability — it is the total absence of a way to certify that an autonomous system is safe to field.',
  players:{ incumbents:['Palantir','Leidos','Lockheed Martin','L3Harris'],
    challengers:['Anduril','Shield AI','Applied Intuition','Scale AI','Vannevar Labs'],
    capital:['a16z American Dynamism','Founders Fund','General Catalyst','8VC','Shield Capital','In-Q-Tel'],
    gov:['DIU','SOCOM','US Army','DARPA'] },
  chokepoints:[
  {k:'Autonomy assurance & certification', use:'Fielding any autonomous system', risk:'High', domestic:95,
   control:'Nobody — the method does not exist', note:'THE gap in the whole chain. The algorithms work. There is no accepted way to prove an autonomous system is safe enough to field, so capability sits in demos. This is a test-and-evaluation problem masquerading as an AI problem.', src:'DoD T&E policy; GAO'},
  {k:'Authority to Operate timelines', use:'Getting software onto networks', risk:'High', domestic:95,
   control:'Accreditation process', note:'Months to years for software that iterates weekly. The cost is not capability, it is relevance decay.', src:'GAO'},
  {k:'Government data access & rights', use:'Training and evaluating models', risk:'Medium', domestic:90,
   control:'Fragmented ownership, unclear rights', note:'The data exists and is legally and practically hard to reach, which advantages whoever is already inside.', src:'Industry'},
  {k:'Cleared software talent', use:'Classified programs', risk:'Medium', domestic:85,
   control:'Clearance throughput', note:'Clearance backlogs, not salaries, are the real hiring constraint at the classified end.', src:'ODNI reporting'},
  {k:'Spectrum-aware and EW-resilient autonomy', use:'Contested environments', risk:'Medium', domestic:85,
   control:'Thin overlap between EW and autonomy communities', note:'Most autonomy is developed assuming clean comms and GPS. That assumption fails first in any real fight.', src:'Industry'},
  ],
  whitespace:[
  {t:'Autonomy assurance as a service', heat:'Hot', kind:'Company',
   d:'If you can produce evidence a program office will accept that an autonomous system is safe, you unlock every stalled autonomy program at once. This is the highest-leverage unbuilt company in the entire value chain: the demand is universal, the incumbents are not trying, and it requires taste in statistics and standards rather than a foundry.'},
  {t:'Simulation-first qualification, formally accepted', heat:'Hot', kind:'Policy / Company',
   d:'Flight test hours cannot scale to the number of autonomy behaviours that need validating. Getting simulated evidence formally accepted in the certification basis — as aviation has partly done — is a policy fight with an enormous software business attached to winning it.'},
  {t:'Model and data provenance for government AI', heat:'Early', kind:'Company',
   d:'When a model informs a targeting decision, someone will eventually need to reconstruct what it was trained on and why it said that. No infrastructure exists for this today, and the first serious incident will create the requirement overnight.'},
  {t:'EW-native autonomy', heat:'Contrarian', kind:'Company',
   d:'Build autonomy that assumes jamming, spoofing and no GPS from the first line of code, rather than bolting resilience on later. The EW and autonomy communities barely talk, which is why this sits open.'},
  {t:'Red-teaming and adversarial evaluation for defense models', heat:'Early', kind:'Company',
   d:'Independent adversarial evaluation of models before fielding. A natural companion to assurance, and a business that benefits from being seen as neutral rather than as a vendor.'},
  ] },

{ id:'launch', n:9, name:'Launch & on-orbit services', short:'Launch & on-orbit',
  domestic:90, risk:'Low',
  bind:'Single supplier', bindWhy:'Roughly 95% domestic and heavily dependent on one company. The cleanest demonstration that "domestic" and "resilient" are different axes.',
  what:'Launch vehicles, upper stages, orbital transfer vehicles, refuelling, servicing, space domain awareness.',
  why:'A genuine American structural advantage, with cost per kilogram down by more than an order of magnitude and a deep bench of new entrants behind the leader.',
  verdict:'Well covered and highly concentrated in one provider. The strategic question is single-provider dependence, not national capability.',
  players:{ incumbents:['SpaceX','Rocket Lab','Northrop Grumman','Boeing Defense'],
    challengers:['Stoke Space','Firefly Aerospace','Impulse Space','Orbit Fab','True Anomaly','K2 Space'],
    capital:['Founders Fund','a16z American Dynamism','Lux Capital','Sequoia'],
    gov:['US Space Force','SDA','NASA','NRO'] },
  chokepoints:[
  {k:'Single-provider concentration', use:'Most US launch mass', risk:'High', domestic:95,
   control:'One company carries the large majority of US launch',
   note:'The inverse of every other row in this view: total domestic capability, serious single-firm dependence. Worth sitting with, because it shows "domestic" and "resilient" are different axes.', src:'FAA/Space Force launch records'},
  {k:'Upper stage & orbital transfer capacity', use:'Getting to the right orbit', risk:'Medium', domestic:85,
   control:'Emerging competitive market', note:'Healthily contested, which is what a working segment looks like.', src:'Industry'},
  {k:'Helium for pressurisation', use:'Launch operations', risk:'Medium', domestic:60,
   control:'Global helium market; Federal reserve divested 2024', note:'A consumable that scrubs launches and that nobody hedges.', src:'BLM'},
  {k:'Range and range safety capacity', use:'Launch cadence', risk:'Medium', domestic:80,
   control:'Two main ranges, aging infrastructure', note:'Cadence growth is starting to press on range throughput and airspace deconfliction rather than on rockets.', src:'Space Force'},
  {k:'On-orbit refuelling ecosystem', use:'Manoeuvre without limit', risk:'Medium', domestic:70,
   control:'Chicken-and-egg', note:'Nobody launches refuelable satellites until fuel is available, and nobody sells fuel until satellites are refuelable. A coordination failure, not a technical one.', src:'Industry'},
  ],
  whitespace:[
  {t:'Break the refuelling deadlock with an anchor buyer', heat:'Hot', kind:'Policy / Company',
   d:'The technology is nearly ready and the market cannot form because of sequencing. A government commitment to buy propellant on orbit — or to mandate refuellable interfaces on new buses — resolves it in one move. Orbit Fab has been waiting on exactly this.'},
  {t:'On-orbit servicing and inspection as a subscription', heat:'Early', kind:'Company',
   d:'Inspection, life extension, repositioning, sold as a recurring service rather than per-mission. Space domain awareness plus manoeuvre is already dual-use, which makes the government the anchor customer and the commercial fleet the growth.'},
  {t:'Responsive launch as an option contract', heat:'Contrarian', kind:'Fintech',
   d:'Sell the right to launch within 24 hours, priced like an option rather than a mission. The customer is buying insurance against losing a satellite, not a rocket — a completely different product from the same asset.'},
  {t:'Point-to-point terrestrial delivery', heat:'Contrarian', kind:'Company',
   d:'Rocket Cargo has funded studies for years. The economics are marginal and the strategic value of moving tonnes anywhere in ninety minutes is not, which makes it a classic case where the government should pay for capability rather than wait for a market.'},
  {t:'Debris removal with an identified payer', heat:'Early', kind:'Policy',
   d:'The technology is closer than the business model. Nobody has answered who pays, and until someone designs that mechanism — liability, insurance discount, or fee at launch — the segment cannot exist.'},
  ] },

{ id:'test', n:10, name:'Test, ranges & sustainment', short:'Test & sustainment',
  domestic:60, risk:'High',
  bind:'Process capacity', bindWhy:'~40 ageing ground facilities against a national hypersonics push. Decades of deferred infrastructure spending, now binding.',
  what:'Wind tunnels, arc jets, flight test ranges, hardware-in-the-loop labs, depot maintenance, spares and obsolescence management.',
  why:'The least glamorous segment and a hard gate on everything upstream. The US is developing next-generation hypersonic systems faster than it is building the infrastructure to test them.',
  verdict:'Systematically underfunded for decades and now visibly binding. Also the segment with the clearest, most boring, most investable gaps.',
  players:{ incumbents:['AEDC / Arnold AFB','NASA facilities','Lockheed Martin','Boeing Defense'],
    challengers:['Kratos','Varda Space','Starfighters Space','Hermeus','GE Aerospace (HyCAT)'],
    capital:['DoD Office of Strategic Capital','Lux Capital','8VC','infrastructure funds'],
    gov:['DIU','US Air Force','NASA','DARPA'] },
  chokepoints:[
  {k:'Hypersonic ground test capacity', use:'Qualifying hypersonic systems', risk:'Critical', domestic:60,
   control:'~40 ageing US ground facilities, oversubscribed',
   note:'Wind tunnels, thermal chambers and test tracks are often decades old, with minimal production base for replacement parts and outdated data collection. FY2026 carries Air Force, Navy and Army line items for tunnel construction, reactivation or modernisation, plus the first new NASA wind tunnel in over 40 years.', src:'Rebuilding.tech; Air & Space Forces Magazine; INN (2026)'},
  {k:'Flight test range availability', use:'All flight programs', risk:'High', domestic:65,
   control:'Limited ranges, airspace deconfliction', note:'Schedule slips attributed to "engineering" are frequently range availability in disguise.', src:'Industry'},
  {k:'Arc jet & materials test', use:'Thermal protection systems', risk:'High', domestic:55,
   control:'Very few facilities', note:'Kratos selected Odon, Indiana in May 2026 for a new mid-tier coupled arc jet and laser facility explicitly to address this gap — a rare case of private capital building national test infrastructure.', src:'Kratos announcement, May 2026'},
  {k:'Depot capacity & spares', use:'Readiness of fielded fleets', risk:'High', domestic:70,
   control:'Depot throughput, obsolete parts', note:'Readiness rates are a supply chain outcome, not a maintenance culture outcome. This is where segment 5 shows up as aircraft not flying.', src:'GAO'},
  {k:'Obsolescence / diminishing sources', use:'Sustaining 30-year systems', risk:'High', domestic:55,
   control:'Vanished suppliers, lost drawings', note:'Sometimes the drawings genuinely no longer exist and the part has to be reverse-engineered from a physical sample.', src:'GAO'},
  {k:'Instrumentation & test data infrastructure', use:'Getting value from each test', risk:'Medium', domestic:65,
   control:'Outdated data collection', note:'When test slots are the scarce resource, extracting more information per slot is the highest-return investment available.', src:'Rebuilding.tech'},
  ],
  whitespace:[
  {t:'Commercial hypersonic test-as-a-service', heat:'Hot', kind:'Company',
   d:'Kratos is building an arc jet, Starfighters is offering F-104 flight test, DIU\'s HyCAT is buying airborne test beds, and every service has FY2026 money for tunnels. Demand is proven, the government is signalling it will pay, and the asset is a financeable piece of infrastructure rather than a science project. The most under-appreciated investable gap in the chain.'},
  {t:'Airborne test beds instead of tunnels', heat:'Hot', kind:'Company',
   d:'Flying a test article on a reusable aircraft or rocket gets real-atmosphere data without waiting years for a tunnel slot. GE is advancing a test bed under HyCAT; Varda gets hypersonic reentry data as a by-product of its pharma business, which is a beautifully oblique way into the market.'},
  {t:'Obsolescence reverse-engineering at the depot', heat:'Early', kind:'Company',
   d:'Scan the part, rebuild the model, qualify a new source, print or machine it. Unglamorous, recurring, enormous installed base, and the alternative is a grounded aircraft.'},
  {t:'Retrofit sensing for predictive maintenance on legacy fleets', heat:'Early', kind:'Company',
   d:'Predictive maintenance assumes instrumented platforms. Most of the fleet is not. Bolt-on sensing plus modelling on a 40-year-old airframe is a bigger market than anything on new-build platforms.'},
  {t:'A regulated exchange for qualified used parts', heat:'Contrarian', kind:'Company',
   d:'Serviceable surplus parts exist in enormous quantities with no trustworthy marketplace, which is exactly why the counterfeit grey market thrives. Provenance plus certification turns a liability into supply.'},
  ] },
];

/* ─── 4. HEADLINE READS ───────────────────────────────────────────── */
const READS = [
  { t:'Risk concentrates left, value concentrates right',
    d:'Segments 1–3 average about 32% domestic coverage. Segments 7–9 average about 90%. The US is close to unbeatable at turning subsystems into fielded capability and dependent on others for the atoms those systems are made of.' },
  { t:'"Domestic" and "secure" are different axes',
    d:'Ammonium perchlorate is 100% domestic and the single highest-risk input in the chain, because there is one plant. US launch is ~95% domestic and carries serious single-firm concentration. Counting import share alone will mislead you in both directions.' },
  { t:'Refining beats mining as the real chokepoint',
    d:'Most "China controls X" claims are about separation and refining, not ore. A mine without a refinery ships concentrate to China and buys the metal back, so segment 2 gates segment 1\'s value.' },
  { t:'The scarce input is often a queue, a permit, or a certificate',
    d:'Switch the spine to "Binding constraint" and only two of ten segments are actually limited by foreign control. Three are limited by having one supplier, four by process capacity, one by the absence of a standard. Several of the best businesses on this page manufacture nothing.' },
  { t:'The government has started acting like an investor',
    d:'A ~15% equity stake in MP Materials with an NdPr price floor, a $620M Office of Strategic Capital loan to Vulcan Elements, a ~$1B direct investment tied to L3Harris\'s motor business. If the customer will fund the capex, the financeability of hard-tech supply businesses changes — and most founders have not repriced that.' },
];

/* ─── 5. PROVENANCE ───────────────────────────────────────────────── */
const META = {
  verified: '2026-09-17',
  status: 'SEED — facts sourced, scores are analyst judgement. See docs/04-data-plan.md.',
  caveat: 'China suspended its export BANS on gallium, germanium and antimony to the US until 27 Nov 2026, but the underlying LICENCE requirements remain in force. Shipments of gallium and germanium to Japan have run at zero in 2026 under licensing alone. Any risk read here is a snapshot of a fast-moving policy environment.',
  sources: [
    ['CSIS', 'China Imposes Its Most Stringent Critical Minerals Export Restrictions Yet', 'https://www.csis.org/analysis/china-imposes-its-most-stringent-critical-minerals-export-restrictions-yet-amidst'],
    ['ORF America', "China's Critical Mineral Export Controls: Background & Chokepoints", 'https://orfamerica.org/newresearch/chinas-critical-mineral-export-controls'],
    ['Pillsbury', 'China Suspends Export Controls on Certain Critical Minerals', 'https://www.pillsburylaw.com/en/news-and-insights/china-suspends-export-controls-certain-critical-minerals-related-items.html'],
    ['The Oregon Group', 'China lifts export ban: gallium, germanium, antimony', 'https://theoregongroup.com/commodities/gallium-germanium/china-lifts-export-ban-gallium-germanium-antimony/'],
    ['The Oregon Group', 'Sanctions, Tariffs, and the Global Titanium Supply', 'https://theoregongroup.com/commodities/titanium/sanctions-tariffs-and-the-global-titanium-supply-catalysts-for-crisis/'],
    ['Federal Register', 'Section 232 Report: Titanium Sponge and National Security', 'https://www.federalregister.gov/documents/2021/10/26/2021-23301/publication-of-a-report-on-the-effect-of-imports-of-titanium-sponge-on-the-national-security-an'],
    ['Breaking Defense', 'With the boom for solid rocket motors, a perilous crunch in the supply chain', 'https://breakingdefense.com/2026/01/with-the-boom-for-solid-rocket-motors-for-missiles-a-perilous-crunch-in-the-supply-chain/'],
    ['Janes', 'Rocket fuel: US Army expanding ammonium perchlorate sources', 'https://www.janes.com/osint-insights/defence-news/weapons/rocket-fuel-us-army-expanding-ammonium-perchlorate-sources-for-artillery'],
    ['MP Materials', 'Public-Private Partnership with the Department of Defense', 'https://mpmaterials.com/news/mp-materials-announces-transformational-public-private-partnership-with-the-department-of-defense-to-accelerate-u-s-rare-earth-magnet-independence/'],
    ['FAS', 'Unpacking the DoD and MP Materials Critical Minerals Partnership', 'https://fas.org/publication/unpacking-dod-and-mp-partnership/'],
    ['The Wire China', 'The Magnet Makers', 'https://www.thewirechina.com/2026/03/15/the-magnet-makers-vulcan-elements-rare-earths/'],
    ['Greenwich Capital Group', 'Why Casting Is the Hidden Bottleneck in Aerospace & Defense', 'https://greenwichgp.com/2026/04/16/why-casting-is-the-hidden-bottleneck-in-aerospace-defense/'],
    ['Deloitte', 'Midyear update: 2026 Aerospace and Defense Industry Outlook', 'https://www.deloitte.com/us/en/insights/industry/aerospace-defense/midyear-update-aerospace-defense-industry-outlook.html'],
    ['Oliver Wyman', 'US defense supply chain: 6 reasons it is falling behind', 'https://www.oliverwyman.com/our-expertise/insights/2026/jul/us-defense-industrial-base-production-ramp.html'],
    ['Rebuilding.tech', 'Closing the Hypersonic Testing Loop', 'https://www.rebuilding.tech/posts/closing-the-hypersonic-testing-loop'],
    ['Air & Space Forces Magazine', "The U.S. Is Playing Catch-Up on Hypersonics", 'https://www.airandspaceforces.com/the-u-s-is-playing-catch-up-on-hypersonics-heres-how/'],
    ['Rare Earth Exchanges', "China's Exclusive Export List for Critical Metals (2026-2027)", 'https://rareearthexchanges.com/news/chinas-exclusive-export-list-for-critical-metals-2026-2027-whos-in-and-why-it-matters/'],
    ['Metal Tech News', 'China curbs tech metal exports to Japan', 'https://www.metaltechnews.com/story/2026/03/25/tech-metals/china-curbs-tech-metal-exports-to-japan/2695.html'],
  ],
};

/* ─── 6. DERIVED GRAPH (constellation view) ───────────────────────── */
const CAP_NAME = Object.fromEntries(CAPS);
const nodes = [], rawLinks = [];
CAPS.forEach(([id, name]) => nodes.push({
  id: name, type: 'capability', val: 46, hq: '', stage: '',
  note: 'A capability cluster — the problem, not the company. Nodes wired here compete, partner, or buy along this axis.'
}));
ORGS.forEach(([name, type, caps, invs, buyers, hq, stage, note]) => {
  nodes.push({ id: name, type, hq, stage, note,
    val: type === 'prime' ? 17 : type === 'gov' ? 14 : type === 'investor' ? 10 : 8 });
  caps.forEach(c => rawLinks.push({ source: name, target: CAP_NAME[c], kind: 'capability' }));
  invs.forEach(i => INV_ID[i] && rawLinks.push({ source: INV_ID[i], target: name, kind: 'investment' }));
  buyers.forEach(b => BUYER_ID[b] && rawLinks.push({ source: name, target: BUYER_ID[b], kind: 'sells to' }));
});
const seen = new Set();
const links = rawLinks.filter(l => {
  const k = l.source + '>' + l.target + '>' + l.kind;
  if (seen.has(k) || l.source === l.target) return false;
  seen.add(k); return true;
});

return { CAPS, ORGS, CAP_NAME, BUYER_ID, INV_ID, nodes, links, SEGMENTS, READS, META };
})();
